/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.SwingUtilities;

/**
 *
 * @author brixd
 */
public class librarian extends javax.swing.JFrame {

    ImageIcon logo = new ImageIcon(getClass().getResource("/img/logo.png"));

    PreparedStatement pst,pst1,pst2 = null;
    ResultSet rs,rsx,rsy = null;
    int i,q,d;
    String BOOKID;
    public String librarian;
    
    static final String USERNAME = "root";
    static final String PASSWORD = "";
    static final String DATACONN = "jdbc:mysql://localhost/setlibrary";
    com.mysql.jdbc.Connection SQLCONN = null;
    
    public librarian() {
        initComponents();
        SQLCONN = (com.mysql.jdbc.Connection) con();
        updateMode();
        setResizable(false);
        setTitle("Librarian Information");
        setIconImage(logo.getImage()); 
    }
    
    public final Connection con(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            SQLCONN = (com.mysql.jdbc.Connection) DriverManager.getConnection(DATACONN,USERNAME,PASSWORD);
        }catch(SQLException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,e);
        }
        return SQLCONN;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        libId = new javax.swing.JTextField();
        libFn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        libMn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        libLn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        libSf = new javax.swing.JTextField();
        libBd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        libNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        libAd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        libEm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        libUn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        libPw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 430));
        setSize(new java.awt.Dimension(570, 430));
        getContentPane().setLayout(null);

        jLabel1.setText("Librarian Identifaction Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 290, 20);

        jLabel2.setText("LIBRARIAN ACCOUNT INFORMATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 360, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 57, 360, 3);

        libId.setEditable(false);
        getContentPane().add(libId);
        libId.setBounds(20, 90, 290, 22);
        getContentPane().add(libFn);
        libFn.setBounds(20, 140, 140, 22);

        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 140, 20);

        jLabel4.setText("Middle Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 120, 140, 20);
        getContentPane().add(libMn);
        libMn.setBounds(170, 140, 140, 22);

        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 120, 140, 20);
        getContentPane().add(libLn);
        libLn.setBounds(320, 140, 140, 22);

        jLabel6.setText("Suffix");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 120, 70, 20);
        getContentPane().add(libSf);
        libSf.setBounds(470, 140, 70, 22);
        getContentPane().add(libBd);
        libBd.setBounds(20, 200, 140, 22);

        jLabel7.setText("Birth Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 180, 140, 20);

        jLabel8.setText("Contact Number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 180, 140, 20);
        getContentPane().add(libNo);
        libNo.setBounds(170, 200, 140, 22);

        jLabel9.setText("Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 240, 290, 20);
        getContentPane().add(libAd);
        libAd.setBounds(20, 260, 520, 22);

        jLabel10.setText("Email");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 180, 140, 20);
        getContentPane().add(libEm);
        libEm.setBounds(320, 200, 140, 22);

        jLabel11.setText("Username");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 300, 140, 20);
        getContentPane().add(libUn);
        libUn.setBounds(20, 320, 140, 22);

        jLabel12.setText("Password");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(170, 300, 140, 20);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(470, 360, 72, 23);
        getContentPane().add(libPw);
        libPw.setBounds(170, 320, 130, 22);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
            try{
                pst = SQLCONN.prepareStatement("update librarian SET `libFName` = ? , `libMName` = ? , `libLName`=? , libSuffix=? , libBDate = ? , "
                        + "libContact = ? , libAddress = ? , libEmail = ? , username = ? , password = ? where libId = ?");
                pst.setString(1,libFn.getText());
                pst.setString(2, libMn.getText());
                pst.setString(3,libLn.getText());
                pst.setString(4,libSf.getText());
                pst.setString(5,libBd.getText());
                pst.setString(6, libNo.getText());
                pst.setString(7,libAd.getText());
                pst.setString(8,libEm.getText());
                pst.setString(9,libUn.getText());
                pst.setString(10,libPw.getText());
                pst.setString(11,libId.getText());
                
                if(JOptionPane.showConfirmDialog(null, "Confirm Update Account","Confirmation",JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
                    pst.executeUpdate();dispose();
                    JOptionPane.showMessageDialog(null,"Account Updated.","Success",JOptionPane.INFORMATION_MESSAGE);
                 }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e,"Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField libAd;
    public javax.swing.JTextField libBd;
    public javax.swing.JTextField libEm;
    public javax.swing.JTextField libFn;
    public javax.swing.JTextField libId;
    public javax.swing.JTextField libLn;
    public javax.swing.JTextField libMn;
    public javax.swing.JTextField libNo;
    public javax.swing.JPasswordField libPw;
    public javax.swing.JTextField libSf;
    public javax.swing.JTextField libUn;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
private boolean isDarkMode = false;
    
     private void updateMode() {
        if (isDarkMode) {
            FlatDarkLaf.install();
        } else {
            FlatLightLaf.install();
        }
        SwingUtilities.updateComponentTreeUI(this);
    }
}
